@prefix OBAN: <http://purl.org/oban/> .

CONSTRUCT {?geneProfile ?phenotype}

WHERE {
?association a OBAN:association
?association OBAN:association_has_predicate OBO:RO_0002200
?association OBAN:association_has_subject ?gene
?association OBAN:association_has_object ?phenotype

BIND(IRI(CONCAT(STR(?gene),"#profile")) AS ?geneProfile)
}