name: Test Makefile

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install yargs
      - run: git clone --depth 1 https://github.com/phenoscape/phenoscape-data.git
      - run: ./test/test-makefile.sh 
